# Critical Security Alerts
# Constitutional Shrinkage Platform

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: critical-security-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/name: security-alerts
    app.kubernetes.io/component: alerting
    prometheus: platform
spec:
  groups:
    - name: critical-security
      interval: 30s
      rules:
        # Authentication Attacks
        - alert: BruteForceAttackDetected
          expr: |
            sum(rate(auth_login_failures_total{reason="invalid_credentials"}[5m])) by (ip) > 10
          for: 2m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Brute force attack detected from {{ $labels.ip }}"
            description: "More than 10 failed login attempts per minute from IP {{ $labels.ip }}"
            runbook_url: "https://wiki.internal/runbooks/brute-force-attack"

        - alert: CredentialStuffingDetected
          expr: |
            count(rate(auth_login_failures_total{reason="invalid_credentials"}[5m]) > 0) by (ip) > 20
          for: 5m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Credential stuffing attack detected"
            description: "Single IP attempting many different usernames"
            runbook_url: "https://wiki.internal/runbooks/credential-stuffing"

        # Data Exfiltration
        - alert: UnusualDataExport
          expr: |
            sum(rate(api_response_bytes_total{endpoint=~".*export.*|.*download.*"}[5m])) by (user_id) > 10000000
          for: 5m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Unusual data export detected"
            description: "User {{ $labels.user_id }} exporting unusually large amounts of data"
            runbook_url: "https://wiki.internal/runbooks/data-exfiltration"

        - alert: BulkDataAccess
          expr: |
            sum(rate(api_requests_total{endpoint=~".*list.*|.*search.*"}[5m])) by (user_id) > 100
          for: 10m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Bulk data access pattern detected"
            description: "User {{ $labels.user_id }} making unusually many data access requests"

        # Voting Integrity
        - alert: VoteManipulationAttempt
          expr: |
            sum(rate(vote_submissions_total[1m])) by (user_id) > 5
          for: 1m
          labels:
            severity: critical
            team: security
            compliance: voting-integrity
          annotations:
            summary: "Vote manipulation attempt detected"
            description: "User {{ $labels.user_id }} submitting votes at suspicious rate"
            runbook_url: "https://wiki.internal/runbooks/vote-manipulation"

        - alert: CoordinatedVotingPattern
          expr: |
            count(sum(rate(vote_submissions_total[5m])) by (bill_id) > 10) > 3
          for: 5m
          labels:
            severity: critical
            team: security
            compliance: voting-integrity
          annotations:
            summary: "Coordinated voting pattern detected"
            description: "Multiple bills receiving coordinated voting activity"

        # Privilege Escalation
        - alert: UnauthorizedAdminAccess
          expr: |
            sum(rate(api_requests_total{endpoint=~"/admin.*", status="403"}[5m])) by (user_id) > 3
          for: 2m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Unauthorized admin access attempts"
            description: "User {{ $labels.user_id }} attempting to access admin endpoints without authorization"

        - alert: RoleEscalationAttempt
          expr: |
            sum(rate(auth_role_change_attempts_total{authorized="false"}[5m])) > 0
          for: 1m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Role escalation attempt detected"
            description: "Attempt to elevate user privileges detected"

        # System Compromise
        - alert: SuspiciousProcessExecution
          expr: |
            sum(rate(container_process_start_total{process_name=~".*sh|.*bash|.*curl|.*wget|.*nc"}[5m])) by (pod) > 5
          for: 2m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Suspicious process execution in container"
            description: "Pod {{ $labels.pod }} executing suspicious processes"

        - alert: ContainerEscapeAttempt
          expr: |
            sum(rate(container_privilege_escalation_attempts_total[5m])) by (pod) > 0
          for: 1m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Container escape attempt detected"
            description: "Pod {{ $labels.pod }} attempting privilege escalation"

        # WAF Critical Events
        - alert: WAFCriticalBlock
          expr: |
            sum(rate(waf_blocked_requests_total{severity="critical"}[5m])) > 10
          for: 2m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "High rate of critical WAF blocks"
            description: "More than 10 critical WAF blocks in the last 5 minutes"

        # Certificate Expiry
        - alert: CertificateExpiringSoon
          expr: |
            (cert_expiry_timestamp_seconds - time()) / 86400 < 7
          for: 1h
          labels:
            severity: critical
            team: security
          annotations:
            summary: "TLS certificate expiring soon"
            description: "Certificate {{ $labels.certificate }} expires in less than 7 days"

        # Database Security
        - alert: DatabaseUnauthorizedAccess
          expr: |
            sum(rate(postgresql_connections_rejected_total{reason="authentication_failed"}[5m])) > 5
          for: 2m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Database authentication failures"
            description: "Multiple failed database authentication attempts"

        # Secrets Exposure
        - alert: SecretsAccessAnomaly
          expr: |
            sum(rate(vault_secret_reads_total[5m])) by (path) > 100
          for: 5m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Unusual secrets access pattern"
            description: "High rate of secrets access for path {{ $labels.path }}"
