// Components
export {
  SkipLinks,
  LiveRegion,
  FocusTrap,
  VisuallyHidden,
  AccessibleIcon,
  DecorativeIcon,
  AccessibleTable,
  FormField,
  FormGroup,
  RadioOption,
  type SkipLink,
  type SkipLinksProps,
  type LiveRegionProps,
  type FocusTrapProps,
  type VisuallyHiddenProps,
  type AccessibleIconProps,
  type DecorativeIconProps,
  type AccessibleTableProps,
  type TableColumn,
  type FormFieldProps,
  type FormGroupProps,
  type RadioOptionProps,
} from './components';

// Hooks
export {
  useAnnounce,
  useFocusReturn,
  useFocusReturnOnUnmount,
  useKeyboardNav,
  useReducedMotion,
  useAnimationDuration,
  useAnimationClass,
  useHighContrast,
  usePrefersHighContrast,
  useFocusVisible,
  useFocusVisibleWithin,
  type AnnouncementPriority,
  type UseAnnounceReturn,
  type UseFocusReturnOptions,
  type UseFocusReturnReturn,
  type NavigationDirection,
  type UseKeyboardNavOptions,
  type ContrastPreferences,
} from './hooks';

// Utils
export {
  checkBasicA11y,
  calculateA11yScore,
  formatViolations,
  hexToRgb,
  parseColor,
  getRelativeLuminance,
  calculateContrastRatio,
  checkContrast,
  formatContrastResult,
  suggestAAAColor,
  generateId,
  resetIdCounter,
  createAriaDescribedBy,
  createAriaLabelledBy,
  createAriaControls,
  createAriaControlled,
  createTabProps,
  createTabPanelProps,
  createDialogProps,
  createLiveRegionProps,
  getAccessibleName,
  type A11yViolation,
  type A11yTestResult,
  type RGB,
  type ContrastResult,
  type AriaRole,
  type AriaControlsProps,
  type AriaControlledProps,
  type TabAriaProps,
  type TabPanelAriaProps,
  type DialogAriaProps,
  type LiveRegionAriaProps,
} from './utils';

// Context
export {
  A11yProvider,
  useA11y,
  useA11yPreferences,
  type A11yPreferences,
  type A11yContextValue,
  type A11yProviderProps,
} from './context/A11yContext';
